### ISSUE TITLE
Donate the project to the Codingteam Foundation

### ISSUE THREAD

**Issue by rexim** [codingteam/pacmacs.el#140]
https://github.com/codingteam
Things that can break during the transition:
- [x] **MELPA** — I believe MELPA uses only `git fetch` to interact with our repo, which will be redirected after the repo transferring. But I think we still need to create an issue for updating the MELPA's recipe
- [x] **Travis CI** — travis actually did a pretty good job at picking up the new repo name after #66. So I hope it will handle the transferring the same way. 
- [x] **Coveralls** — after #66 we had to remove and then add the project again to make the coverage work again. We need to create an issue for that.
- [x] **External HTTP links to the repo** — most of the external links were created after #66, so after the transferring they will be redirected. Nothing to be worried about.

Some info on repo transferring: https://help.github.com/articles/transferring-a-repository/

**Comment by ForNeVeR** [comment]
Please consider whether it could create any problems for melpa. The repository address will change, you know.

**Comment by rexim** [comment]
@ForNeVeR thanks! That's why I've put the TBD in the description. :) I am going to create a list of such things to keep in mind during the actual repo transition

**Comment by ForNeVeR** [comment]
I think that you suggested discussion here, so I'm discussing it :3

**Comment by rexim** [comment]
Yep, of course it's for discussion as well. Any of your suggestions or questions regarding this topic are welcome here. ;)

**Comment by rexim** [comment]
@ForNeVeR I actually have some concerns. What if in the future we will decided to group repos that are related to a single project (like horta related repos, keter related repos and even pacmacs related repos, because of server side for #37) by putting them to different organizations to avoid the cluttering of the main organization. In this case we will need to transfer this repo one more time. Will GitHub actually preserve the correct redirects after all of this renamings and transferrings?

**Comment by ForNeVeR** [comment]
Should we really care so much about these redirects?

**Comment by rexim** [comment]
@ForNeVeR personally, I do care about external links on different Internet services because they are assets of the project, and they are part of the project reputation. And we do care about project reputation, because it's a reputation of Codingteam itself.

That's ok if you don't know the answer for my question. I'll contact the GitHub's support.

**Comment by rexim** [comment]
Just did a little experiment by myself.
1. Created repo `hello`
2. Renamed `hello` to `world`
3. Went to `rexim/hello` by HTTP, got redirected to `rexim/world`
4. Renamed `world` to `foo`
5. Went to `rexim/hello` by HTTP, got redirected to `rexim/foo`
6. Went to `rexim/world` by HTTP, got redirected to `rexim/foo`

Looks like multiple renaming are handled pretty well. I will assume that redirects after transferring work similarly. And of course will check everything after the actual transfer.

**Comment by rexim** [comment]
The repo has been transferred. Created #144 and #145 to address the rest of the problems in the description. Closing the issue.
